import { Card } from '../../../interfaces'
import Set from '../Unleashed'

const card: Card = {
	name: {
		en: "Beldum",
		fr: "Terhal",
		de: "Tanhel"
	},

	illustrator: "Wataru Kawahara",
	rarity: "Common",
	category: "Pokemon",
	set: Set,

	dexId: [
		374,
	],

	hp: 60,

	types: [
		"Psychic",
	],

	stage: "Basic",

	attacks: [
		{
			cost: [
				"Psychic",
			],
			name: {
				en: "Reaction",
				fr: "Réagir",
				de: "Reaktion"
			},
			effect: {
				en: "You may switch Beldum with 1 of your Benched Pokémon.",
				fr: "Vous pouvez échanger Terhal avec un Pokémon de votre Banc.",
				de: "Du kannst Tanhel gegen 1 Pokémon auf deiner Bank austauschen."
			},
			damage: 10,

		},
	],

	weaknesses: [
		{
			type: "Psychic",
			value: "×2"
		},
	],

	retreat: 2,

	description: {
		en: "The magnetic force generated by its body repels the ground’s natural magnetism, letting it float."
	},

	variants: [
		{
			type: "normal"
		},
		{
			type: "reverse"
		},
	],

	thirdParty: {
		cardmarket: 279200,
		tcgplayer: 83791
	}
}

export default card
