import { Card } from 'models/database/card'
import Set from '../Undaunted'

const card: Card = {
	name: {
		'en-us': "Beldum",
		'fr-fr': "Terhal",
		'de-de': "Tanhel"
	},

	illustrator: "TOKIYA",
	rarity: "Common",
	category: "Pokemon",
	set: Set,

	dexId: [374],

	hp: 50,

	types: [
		"Metal"
	],

	stage: "Basic",

	attacks: [
		{
			cost: [
				"Metal",
			],
			name: {
				'en-us': "Lunge Out",
				'fr-fr': "Allonger",
				'de-de': "Sprungangriff"
			},

			damage: 10,

		},
		{
			cost: [
				"Metal",
				"Metal",
				"Colorless",
			],
			name: {
				'en-us': "Single Smash",
				'fr-fr': "Simplécrasement",
				'de-de': "Einzelstoß"
			},
			effect: {
				'en-us': "Flip a coin. If tails, this attack does nothing.",
				'fr-fr': "Lancez une pièce. Si c’est pile, cette attaque ne fait rien.",
				'de-de': "Wirf 1 Münze. Bei \"Zahl\" hat dieser Angriff keine Auswirkungen."
			},
			damage: 50,

		},
	],

	weaknesses: [
		{
			type: "Fire",
			value: "×2"
		},
	],

	resistances: [
		{
			type: "Psychic",
			value: "-20"
		},
	],

	retreat: 1,

	description: {
		'en-us': "The magnetic force generated by its body repels the ground’s natural magnetism, letting it float."
	},

	variants: [
		{
			type: "normal",
			thirdParty: {
				cardmarket: 279296,
				tcgplayer: 83792
			}
		},
		{
			type: "reverse",
			thirdParty: {
				cardmarket: 279296,
				tcgplayer: 83792
			}
		}
	],

}

export default card
