services:
  stable:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - MAX_WORKERS=2
      - TCGCSV_USER_AGENT=TCGDex-localDev/1.0.0
    ports:
      - 3000:3000