import { Card } from 'models/database/card'
import Set from '../Unleashed'

const card: Card = {
	name: {
		'en-us': "Beldum",
		'fr-fr': "Terhal",
		'de-de': "Tanhel"
	},

	illustrator: "Wataru Kawahara",
	rarity: "Common",
	category: "Pokemon",
	set: Set,

	dexId: [374],

	hp: 60,

	types: [
		"Psychic"
	],

	stage: "Basic",

	attacks: [
		{
			cost: [
				"Psychic",
			],
			name: {
				'en-us': "Reaction",
				'fr-fr': "Réagir",
				'de-de': "Reaktion"
			},
			effect: {
				'en-us': "You may switch Beldum with 1 of your Benched Pokémon.",
				'fr-fr': "Vous pouvez échanger Terhal avec un Pokémon de votre Banc.",
				'de-de': "Du kannst Tanhel gegen 1 Pokémon auf deiner Bank austauschen."
			},
			damage: 10,

		},
	],

	weaknesses: [
		{
			type: "Psychic",
			value: "×2"
		},
	],

	retreat: 2,

	description: {
		'en-us': "The magnetic force generated by its body repels the ground’s natural magnetism, letting it float."
	},

	variants: [
		{
			type: "normal",
			thirdParty: {
				tcgplayer: 83791,
				cardmarket: 279200
			}
		},
		{
			type: "reverse",
			thirdParty: {
				tcgplayer: 83791,
				cardmarket: 279200
			}
		},
	],

}

export default card
