import { Card } from "models/database/card";
import Set from "../Paldean Wonders";

const card: Card = {
  set: Set,
  name: {
		'fr-fr': "Fulgulairo",
		'en-us': "Kilowattrel",
		'es-es': "Kilowattrel",
		'it-it': "Kilowattrel",
		'pt-br': "Kilowattrel",
		'de-de': "Voltrean"
  },
  illustrator: "Pani Kobayashi",
  rarity: "Two Diamond",
  category: "Pokemon",
  hp: 90,
  types: ["Lightning"],
  dexId: [941],
  evolveFrom: {
		'fr-fr': "Zapétrel",
		'en-us': "Wattrel",
		'es-es': "Wattrel",
		'it-it': "Wattrel",
		'pt-br': "Wattrel",
		'de-de': "Voltrel"
  },
  description: {
    en: "It uses its throat sac to store electricity generated by its wings. There's hardly any oil in its feathers, so it is a poor swimmer.",
  },
  stage: "Stage1",
  attacks: [
    {
      name: {
        en: "Speed Wing",
        fr: "Ailes Vives",
        es: "Ala Veloz",
        'es-mx': "Ala Veloz",
        de: "Turboschwinge",
        it: "Alaveloce",
        pt: "Asa da Velocidade"
      },
      damage: "40",
      cost: ["Lightning"],
    },
  ],
  weaknesses: [
    {
      type: "Lightning",
      value: "+20",
    },
  ],
};

export default card;