import { Card } from "../../../interfaces";
import Set from "../Paldean Wonders";

const card: Card = {
  set: Set,
  name: {
		fr: "Fulgulairo",
		en: "Kilowattrel",
		es: "Kilowattrel",
		it: "Kilowattrel",
		pt: "Kilowattrel",
		de: "Voltrean"
  },
  illustrator: "Pani Kobayashi",
  rarity: "Two Diamond",
  category: "Pokemon",
  hp: 90,
  types: ["Lightning"],
  dexId: [941],
  evolveFrom: {
		fr: "Zapétrel",
		en: "Wattrel",
		es: "Wattrel",
		it: "Wattrel",
		pt: "Wattrel",
		de: "Voltrel"
  },
  description: {
    en: "It uses its throat sac to store electricity generated by its wings. There's hardly any oil in its feathers, so it is a poor swimmer.",
  },
  stage: "Stage1",
  attacks: [
    {
      name: {
        en: "Speed Wing",
        fr: "Ailes Vives",
        es: "Ala Veloz",
        'es-mx': "Ala Veloz",
        de: "Turboschwinge",
        it: "Alaveloce",
        pt: "Asa da Velocidade"
      },
      damage: "40",
      cost: ["Lightning"],
    },
  ],
  weaknesses: [
    {
      type: "Lightning",
      value: "+20",
    },
  ],
};

export default card;