name: New Set
description: Issue Template used when a new set has been announced by TPC
title: "new set: {Set Name}"
labels: [database]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this set informations
  - type: input
    id: source
    attributes:
      label: Source
      description: Where did you find out about this new set (domain name MUST be pokemon.com)
      placeholder: "ex: https://www.pokemon.com/us/pokemon-tcg/sword-shield-evolving-skies/explore-and-watch/"
    validations:
      required: true
