/**
 * Generate Pokédex Repository
 *
 * Reads pokemon-species.json and generates TypeScript files for the Pokédex dataset.
 * Each species gets its own .ts file with all localized names.
 *
 * Usage:
 *   bun run generate-pokedex-repo.ts
 *
 * Output:
 *   - data/Pokedex/{dexId}.ts files (one per species)
 *   - data/Pokedex.ts index file
 */

import fs from 'fs'
import path from 'path'
import { getRepoPaths } from './path-utils'
import { SupportedLanguages } from '../../interfaces'

interface SourcePokemon {
	dexId: number
	englishName: string
	names: Record<string, string>
	forms: string[]
	evolvesFrom?: number | null
	evolvesTo?: number[]
}

// All supported languages from interfaces.d.ts
const SUPPORTED_LANGS: SupportedLanguages[] = [
	'en', 'fr', 'es', 'es-mx', 'it', 'pt', 'pt-br', 'pt-pt', 'de', 'nl', 'pl', 'ru',
	'ja', 'ko', 'zh-tw', 'id', 'th', 'zh-cn'
]

function padDexId(dexId: number): string {
	return dexId.toString().padStart(4, '0')
}

function buildPokemonImageUrl(dexId: number): string {
	// Official Pokémon.com artwork - no text, universal for all languages
	const paddedDex = dexId.toString().padStart(3, '0')
	return `https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/detail/${paddedDex}.png`
}

function escapeString(str: string): string {
	return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
}

function generateSpeciesFile(pokemon: SourcePokemon): string {
	const namesEntries: string[] = []

	// Generate names for all supported languages
	for (const lang of SUPPORTED_LANGS) {
		const name = pokemon.names[lang] ?? ''
		namesEntries.push(`\t\t${lang.includes('-') ? `"${lang}"` : lang}: "${escapeString(name)}"`)
	}

	const formsArray = pokemon.forms.map((f) => `"${escapeString(f)}"`).join(', ')

	// Evolution data
	const evolvesFrom = pokemon.evolvesFrom ?? null
	const evolvesTo = pokemon.evolvesTo ?? []
	const evolvesToArray = evolvesTo.length > 0 ? evolvesTo.join(', ') : ''

	return `import { PokemonSpecies } from '../interfaces'

const species: PokemonSpecies = {
	dexId: ${pokemon.dexId},
	englishName: "${escapeString(pokemon.englishName)}",
	names: {
${namesEntries.join(',\n')}
	},
	forms: [${formsArray}],
	image: "${buildPokemonImageUrl(pokemon.dexId)}",
	evolvesFrom: ${evolvesFrom === null ? 'null' : evolvesFrom},
	evolvesTo: [${evolvesToArray}]
}

export default species
`
}

function generateIndexFile(pokemonList: SourcePokemon[]): string {
	const imports: string[] = []
	const exports: string[] = []

	for (const pokemon of pokemonList) {
		const paddedId = padDexId(pokemon.dexId)
		const varName = `species${paddedId}`
		imports.push(`import ${varName} from './${paddedId}'`)
		exports.push(`\t${varName}`)
	}

	return `// Auto-generated Pokédex index
// Generated by generate-pokedex-repo.ts

${imports.join('\n')}

export {
${exports.join(',\n')}
}

export const allSpecies = [
${exports.join(',\n')}
]
`
}

async function main() {
	const { scriptsDir, repoRoot } = getRepoPaths(import.meta.url)

	// Read source data
	const sourcePath = path.join(scriptsDir, 'pokemon-species.json')
	console.log(`[i] Reading source: ${sourcePath}`)

	if (!fs.existsSync(sourcePath)) {
		console.error('[x] pokemon-species.json not found. Run download-pokedex.ts first.')
		process.exit(1)
	}

	const rawData = fs.readFileSync(sourcePath, 'utf-8')
	const pokemonList: SourcePokemon[] = JSON.parse(rawData)

	console.log(`[i] Found ${pokemonList.length} Pokémon species`)

	// Create output directory
	const outputDir = path.join(repoRoot, 'pokedex')
	if (!fs.existsSync(outputDir)) {
		fs.mkdirSync(outputDir, { recursive: true })
	}

	// Generate individual species files
	console.log('[i] Generating species files...')
	let generatedCount = 0

	for (const pokemon of pokemonList) {
		const paddedId = padDexId(pokemon.dexId)
		const filePath = path.join(outputDir, `${paddedId}.ts`)
		const content = generateSpeciesFile(pokemon)

		fs.writeFileSync(filePath, content)
		generatedCount++

		if (generatedCount % 100 === 0) {
			console.log(`[i] Generated ${generatedCount}/${pokemonList.length} species...`)
		}
	}

	// Generate index file
	const indexPath = path.join(outputDir, 'index.ts')
	const indexContent = generateIndexFile(pokemonList)
	fs.writeFileSync(indexPath, indexContent)

	console.log('')
	console.log(`[OK] Generated ${generatedCount} species files in: ${outputDir}`)
	console.log(`[OK] Generated index file: ${indexPath}`)

	// Print sample
	console.log('')
	console.log('Sample entries:')
	for (const pokemon of pokemonList.slice(0, 3)) {
		console.log(`  #${padDexId(pokemon.dexId)} ${pokemon.englishName}`)
		console.log(`     FR: ${pokemon.names.fr || '(empty)'}`)
		console.log(`     JA: ${pokemon.names.ja || '(empty)'}`)
	}
}

main().catch((error) => {
	console.error('[x] Fatal error:', error)
	process.exit(1)
})

