import { Card } from "../../../interfaces"
import Set from "../Fantastical Parade"

const card: Card = {
	set: Set,

	name: {
		en: "Bellibolt"
	},

	illustrator: "Oswaldo KATO",
	rarity: "Two Diamond",
	category: "Pokemon",
	hp: 130,
	types: ["Lightning"],

	evolveFrom: {
		en: "Tadbulb"
	},

	description: {
		en: "What appear to be eyeballs are actually organs\nfor discharging the electricity generated by\nBellibolt's belly-button dynamo."
	},

	stage: "Stage1",

	attacks: [{
		name: {
			en: "Electric Ball"
		},

		damage: 80,
		cost: ["Lightning", "Lightning", "Colorless"]
	}],

	weaknesses: [{
		type: "Fighting",
		value: "+20"
	}],

	retreat: 3
}

export default card