import { Card } from "../../../interfaces";
import Set from "../Paldean Wonders";

const card: Card = {
  set: Set,
  name: {
    en: "Kilowattrel",
  },
  illustrator: "Pani Kobayashi",
  rarity: "Two Diamond",
  category: "Pokemon",
  hp: 90,
  types: ["Lightning"],
  dexId: [941],
  evolveFrom: {
    en: "Wattrel",
  },
  description: {
    en: "It uses its throat sac to store electricity generated by its wings. There's hardly any oil in its feathers, so it is a poor swimmer.",
  },
  stage: "Stage1",
  attacks: [
    {
      name: {
        en: "Speed Wing",
      },
      damage: "40",
      cost: ["Lightning"],
    },
  ],
  weaknesses: [
    {
      type: "Lightning",
      value: "+20",
    },
  ],
};

export default card;