name: Card Info Comment

on:
  pull_request_target:
    types: [opened, synchronize]
    paths:
      - 'data/**/*.ts'
      - 'data-asia/**/*.ts'

jobs:
  card-info-comment:
    runs-on: ubuntu-latest
    continue-on-error: true
    defaults:
      run:
        working-directory: .github/scripts
    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: Run load-cards script
        id: load-cards
        run: bun load-cards.js
        env:
          INPUT_GITHUB-TOKEN: ${{ secrets.TCGDEX_BOT }}
